apiVersion: apps/v1
kind: Deployment
metadata:
  name: gsc-with-mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gsc-with-mysql
  template:
    metadata:
      labels:
        app: gsc-with-mysql
    spec:
      containers:
      - name: gsc-mysql
        image: aks01containerregistry.azurecr.io/gsc-mysql:debug
        ports:
        - containerPort: 3306
        resources:
          limits:
            kubernetes.azure.com/sgx_epc_mem_in_MiB: 16
          requests:
            kubernetes.azure.com/sgx_epc_mem_in_MiB: 16
        volumeMounts:
        - name: var-run-aesmd
          mountPath: /var/run/aesmd
        - name: test-db-encrypted
          mountPath: /var/run/test_db_encrypted    
        env:
        - name:  SECRET_PROVISION_SERVERS
          value:  "verifierbymr.eastus2.cloudapp.azure.com:4433" #DNS of verifier with port
      volumes:
      - name: var-run-aesmd
        hostPath:
          path: /var/run/aesmd
      - name: test-db-encrypted
        hostPath:
          path: /var/run/test_db_encrypted
---
apiVersion: v1
kind: Service
metadata:
  name: gsc-mysql
spec:
  selector:
    app.kubernetes.io/name: gsc-with-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306