apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-mysql
  template:
    metadata:
      labels:
        app: test-mysql
    spec:
      containers:
      - name: test-mysql
        image: aks01containerregistry.azurecr.io/gsc-mysql:test
        ports:
        - containerPort: 3306
        resources:
          limits:
            kubernetes.azure.com/sgx_epc_mem_in_MiB: 16
          requests:
            kubernetes.azure.com/sgx_epc_mem_in_MiB: 16
        volumeMounts:
        - name: var-run-aesmd
          mountPath: /var/run/aesmd  
        - name: test-db-encrypted
          mountPath: /var/run/test_db_encrypted
      volumes:
      - name: var-run-aesmd
        hostPath:
          path: /var/run/aesmd
      - name: test-db-encrypted
        hostPath:
          path: /var/run/test_db_encrypted
---
apiVersion: v1
kind: Service
metadata:
  name: test-mysql
spec:
  selector:
    app.kubernetes.io/name: test-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306